平成 28/1/5 18:39:37 にビルドを開始しました。
     1>ノード 2 上のプロジェクト "E:\git\C_py\c-py\c-py\c-py.vcxproj" (Build ターゲット)。
     1>Link:
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\link.exe /ERRORREPORT:PROMPT /OUT:"E:\git\C_py\c-py\Release\c-py.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:C:\Python33\Lib /LIBPATH:C:\Python33\libs python33.lib python3.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:\git\C_py\c-py\Release\c-py.pdb" /SUBSYSTEM:CONSOLE /OPT:REF /OPT:ICF /LTCG /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:\git\C_py\c-py\Release\c-py.lib" /MACHINE:X86 /SAFESEH Release\main.obj
     1>main.obj : error LNK2001: 外部シンボル "__imp__Py_Initialize" は未解決です。
     1>main.obj : error LNK2001: 外部シンボル "__imp__PyArg_Parse" は未解決です。
     1>main.obj : error LNK2001: 外部シンボル "__imp__PyImport_ImportModule" は未解決です。
     1>main.obj : error LNK2001: 外部シンボル "__imp__PyObject_CallMethod" は未解決です。
     1>main.obj : error LNK2001: 外部シンボル "__imp__Py_Finalize" は未解決です。
     1>E:\git\C_py\c-py\Release\c-py.exe : fatal error LNK1120: 5 件の未解決の外部参照
     1>プロジェクト "E:\git\C_py\c-py\c-py\c-py.vcxproj" (Build ターゲット) のビルドが終了しました -- 失敗。

ビルドに失敗しました。

経過時間 00:00:00.10
